### ISSUE TITLE
pqdaemon exception

### ISSUE THREAD

**Issue by mikeshultz** [mikeshultz/pyqual#43]
This ended up in `pyqual.log`.

    Running pqrun and pqme
    Traceback (most recent call last):
      File "/usr/bin/pqdaemon.py", line 5, in <module>
        pkg_resources.run_script('PyQual==1.0.5', 'pqdaemon.py')
      File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 499, in run_script
        self.require(requires)[0].run_script(script_name, ns)
      File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1239, in run_script
        execfile(script_filename, namespace, namespace)
      File "/usr/lib/python2.7/site-packages/PyQual-1.0.5-py2.7.egg/EGG-INFO/scripts/pqdaemon.py", line 42, in <module>
        daemon_runner.do_action()
      File "/usr/lib/python2.7/site-packages/daemon/runner.py", line 189, in do_action
        func(self)
      File "/usr/lib/python2.7/site-packages/daemon/runner.py", line 134, in _start
        self.app.run()
      File "/usr/lib/python2.7/site-packages/PyQual-1.0.5-py2.7.egg/EGG-INFO/scripts/pqdaemon.py", line 36, in run
        pqmessage.main()
      File "/usr/lib/python2.7/site-packages/PyQual-1.0.5-py2.7.egg/EGG-INFO/scripts/pqmessage.py", line 174, in main
        for key, val in data.iteritems():
    AttributeError: 'list' object has no attribute 'iteritems'

**Comment by mikeshultz** [comment]
Problem was bad resultData.  Added some simple debugging output to help diagnose the problems.  At some point better error handling should be done.
