### ISSUE TITLE
Saving users trace

### ISSUE THREAD

**Issue by mikeshultz** [mikeshultz/pyqual#51]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.4/site-packages/pyqual-2.0.0-py3.4.egg/EGG-INFO/scripts/pqweb.py", line 493, in POST
    (username, auth.hash(password), email)
  File "/usr/local/lib/python3.4/site-packages/pyqual-2.0.0-py3.4.egg/pyqual/auth.py", line 73, in hash
    self.hashObj.update(password)
TypeError: Unicode-objects must be encoded before hashing
```

**Comment by mikeshultz** [comment]
38c7338
